### ISSUE TITLE
[REQ] Support for admin system

### ISSUE THREAD

**Issue by crashzk** [stefanx111/cs2-SimpleResetScore#2]
Can we expect support for the admin system? In other words, only those who have access to flags use the command.

**Comment by stefanx111** [comment]
Download this version -> [1.0.1](https://github.com/stefanx111/cs2-SimpleResetScore/releases/download/1.0.1/cs2-SimpleResetScore.zip)
In `configs/plugins/ResetScore/ResetScore.json` set `OnlyAdmins` on `true`
Set for your admins this flag `@resetscore/admin`
